language: bash
matrix:
  include:
    - name: Linux Ubuntu 16 - g++ 5
      os: linux
      dist: xenial
      compiler: gcc
    - name: Linux Ubuntu 18 - g++ 7
      os: linux
      dist: bionic
      compiler: gcc
    - name: Linux Ubuntu 18 - clang 7
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CXX=clang++
    - name: MacOSX 10.14 - XCode 11
      os: osx
      osx_image: xcode11
      compiler: clang
    - name: Windows - Visual Studio 2017
      os: windows
      env:
        - CHOCO_PYTHON="/c/Python37"
      before_install:
        - choco install python --version 3.7.4
        - export PATH=$CHOCO_PYTHON:$PATH
      install:
        # git bash changes the codepage to 65001 which breaks waf's msvc tool,
        # so we run the configure step in powershell using the 850 codepage
        - powershell "chcp 850; python --version; python waf configure"
      script:
        - powershell "chcp 850; python waf build -v"
        # Network tests are terribly slow on Windows, so we skip those
        - powershell "chcp 850; python waf --run_tests --skip_network_tests"
install:
  - python waf configure
script:
  - python waf build -v
  - python waf --run_tests
